---
name: LuckyPot
main: LuckyPot\Main
version: 1.2
api:
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA11
author: Vlcnpvp
commands:
  addpot:
    desctiption: Add Floating Text
    permission: luckypot.addpot
...
